### PR TITLE
Modify OpenShift template and remove .s2i

### PR DESCRIPTION
**Pull request by CermakM**
- template modifications to account for Thoth migration
- remove .s2i folder to use common setup

- remove creation timestamps
- use centos based build image
- use pipenv

Signed-off-by: Marek Cermak <macermak@redhat.com>

modified:   openshift/buildConfig-template.yaml
deleted:    .s2i/

### CODE REVIEW

**Comment by CermakM** [comment]
Closes #10 and #11

**Comment by ghost** [comment]
Build failed.

- [thoth-coala ](https://zuul.thoth-station.ninja/logs/13/13/46fc472ef090e33f02ea122f943cafedc348ade8/check/thoth-coala/cd6966e/) : FAILURE in 2m 04s

**Comment by CermakM** [comment]
Also closes #12

**Comment by CermakM** [comment]
recheck

**Comment by fridex** [comment]
@goern it looks like zuul was not triggered

**Comment by CermakM** [comment]
recheck

**Pull request merged**
